defmodule Dbk.Repo.Migrations.AddSubjectAndTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tables, primary_key: false) do
      add :subject_id,
          references(:subjects,
            column: :id,
            name: "tables_subject_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          )

      add :variables, :bigint
      add :active, :boolean, null: false
      add :latest_period, :text
      add :first_period, :text
      add :updated, :utc_datetime
      add :unit, :text
      add :text, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create table(:subjects, primary_key: false) do
      add :parent_id,
          references(:subjects,
            column: :id,
            name: "subjects_parent_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          )

      add :has_subjects, :boolean
      add :active, :boolean
      add :description, :text, null: false
      add :id, :bigint, null: false, primary_key: true
    end

    create unique_index(:subjects, [:id], name: "subjects_id_index")
  end

  def down do
    drop_if_exists unique_index(:subjects, [:id], name: "subjects_id_index")

    drop constraint(:subjects, "subjects_parent_id_fkey")

    drop table(:subjects)

    drop constraint(:tables, "tables_subject_id_fkey")

    drop table(:tables)
  end
end