defmodule Numeri.Repo.Migrations.Init do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:variables, primary_key: false) do
      add :time, :boolean
      add :elimination, :boolean
      add :order, :bigint
      add :text, :text
      add :id, :text, null: false, primary_key: true
    end

    create table(:variable_values, primary_key: false) do
      add :variable_id,
          references(:variables,
            column: :id,
            name: "variable_values_variable_id_fkey",
            type: :text,
            on_delete: :delete_all
          ),
          null: false

      add :text, :text
      add :value_id, :text
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:variable_values, [:value_id, :variable_id],
             name: "variable_values_unique_value_index"
           )

    create table(:users, primary_key: false) do
      add :email, :citext, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :created_at, :utc_datetime_usec, null: false
      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:tables, primary_key: false) do
      add :subject_id,
          references(:subjects,
            column: :id,
            name: "tables_subject_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          )

      add :active, :boolean, null: false
      add :latest_period, :text
      add :first_period, :text
      add :updated, :utc_datetime
      add :unit, :text
      add :text, :text, null: false
      add :id, :text, null: false, primary_key: true
    end

    create table(:table_variables, primary_key: false) do
      add :variable_id,
          references(:variables,
            column: :id,
            name: "table_variables_variable_id_fkey",
            type: :text,
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :table_id,
          references(:tables,
            column: :id,
            name: "table_variables_table_id_fkey",
            type: :text,
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:table_variables, [:table_id, :variable_id],
             name: "table_variables_unique_table_variable_index"
           )

    create table(:subjects, primary_key: false) do
      add :parent_id,
          references(:subjects,
            column: :id,
            name: "subjects_parent_id_fkey",
            type: :bigint,
            on_delete: :delete_all
          )

      add :has_subjects, :boolean
      add :active, :boolean
      add :description, :text, null: false
      add :id, :bigint, null: false, primary_key: true
    end

    create table(:facts, primary_key: false) do
      add :concept_id,
          references(:concepts, column: :id, name: "facts_concept_id_fkey", type: :bigint)

      add :extra_attributes, :map
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:fact_dimension_values, primary_key: false) do
      add :dimension_value_id, :bigint
      add :fact_id, :bigint
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:dimensions, primary_key: false) do
      add :description, :text
      add :name, :text
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:dimension_values, primary_key: false) do
      add :dimension_id,
          references(:dimensions,
            column: :id,
            name: "dimension_values_dimension_id_fkey",
            type: :bigint
          )

      add :metadata, :map
      add :value, :map
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:concepts, primary_key: false) do
      add :extra_attributes, :map
      add :data_source, :text
      add :description, :text
      add :name, :text
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:concept_dimensions, primary_key: false) do
      add :dimension_id, :bigint
      add :concept_id, :bigint
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:concept_dimensions)

    drop table(:concepts)

    drop constraint(:dimension_values, "dimension_values_dimension_id_fkey")

    drop table(:dimension_values)

    drop table(:dimensions)

    drop table(:fact_dimension_values)

    drop constraint(:facts, "facts_concept_id_fkey")

    drop table(:facts)

    drop constraint(:subjects, "subjects_parent_id_fkey")

    drop table(:subjects)

    drop_if_exists unique_index(:table_variables, [:table_id, :variable_id],
                     name: "table_variables_unique_table_variable_index"
                   )

    drop constraint(:table_variables, "table_variables_table_id_fkey")

    drop constraint(:table_variables, "table_variables_variable_id_fkey")

    drop table(:table_variables)

    drop constraint(:tables, "tables_subject_id_fkey")

    drop table(:tables)

    drop table(:tokens)

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop table(:users)

    drop_if_exists unique_index(:variable_values, [:value_id, :variable_id],
                     name: "variable_values_unique_value_index"
                   )

    drop constraint(:variable_values, "variable_values_variable_id_fkey")

    drop table(:variable_values)

    drop table(:variables)
  end
end