defmodule :"Elixir.Numeri.Repo.Migrations.AddedExtraAttributeToFact" do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:facts) do
      add :extra_attributes, :map
    end
  end

  def down do
    alter table(:facts) do
      remove :extra_attributes
    end
  end
end

